"""Add pincode field to Farm model

Revision ID: 6938f3c07304
Revises: 
Create Date: 2025-03-31 20:42:01.982954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6938f3c07304'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('otp_verification')
    op.drop_table('farm')
    op.drop_table('food_recommendation')
    op.drop_table('language')
    op.drop_table('animal')
    op.drop_table('health_record')
    op.drop_table('user')
    op.drop_table('animal_type')
    op.drop_table('analysis_result')
    op.drop_table('veterinary_service')
    op.drop_table('medication_info')
    op.drop_table('disease_outbreak')
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pincode', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_column('pincode')

    op.create_table('disease_outbreak',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('animal_type', sa.VARCHAR(length=7), nullable=False),
    sa.Column('disease_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('district', sa.VARCHAR(length=100), nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('severity', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('reported_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('animal_type', sa.VARCHAR(length=7), nullable=False),
    sa.Column('disease', sa.VARCHAR(length=100), nullable=False),
    sa.Column('medication_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dosage_formula', sa.VARCHAR(length=100), nullable=True),
    sa.Column('administration', sa.VARCHAR(length=100), nullable=False),
    sa.Column('frequency', sa.VARCHAR(length=100), nullable=False),
    sa.Column('duration', sa.VARCHAR(length=100), nullable=False),
    sa.Column('warning', sa.TEXT(), nullable=True),
    sa.Column('alternative_medication', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veterinary_service',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=False),
    sa.Column('district', sa.VARCHAR(length=100), nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), nullable=False),
    sa.Column('contact_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('specialization', sa.VARCHAR(length=100), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('operating_hours', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('animal_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('analysis_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('result', sa.VARCHAR(length=100), nullable=False),
    sa.Column('confidence', sa.FLOAT(), nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('recommendations', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(length=15), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=200), nullable=False),
    sa.Column('language', sa.VARCHAR(length=2), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile_number')
    )
    op.create_table('health_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('animal_id', sa.INTEGER(), nullable=False),
    sa.Column('disease', sa.VARCHAR(length=100), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('symptoms', sa.TEXT(), nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=200), nullable=True),
    sa.Column('treatment', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('type', sa.VARCHAR(length=7), nullable=False),
    sa.Column('breed', sa.VARCHAR(length=100), nullable=True),
    sa.Column('age', sa.FLOAT(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('native_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('food_recommendation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('animal_type', sa.VARCHAR(length=7), nullable=False),
    sa.Column('food_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('nutrition_info', sa.TEXT(), nullable=True),
    sa.Column('benefits', sa.TEXT(), nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=200), nullable=True),
    sa.Column('is_low_cost', sa.BOOLEAN(), nullable=True),
    sa.Column('recommended_for_disease', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farm',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('farm_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), nullable=False),
    sa.Column('district', sa.VARCHAR(length=100), nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_verification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(length=15), nullable=False),
    sa.Column('otp', sa.VARCHAR(length=6), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expiry_time', sa.DATETIME(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('notification_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('related_disease', sa.VARCHAR(length=100), nullable=True),
    sa.Column('distance_km', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
